name: Ashoo Masonry
favicon: null
layout_spectrum: 0.7072608880698681
typography_spectrum: 0.935921210097149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13701240648515522
  lightness: 0.8203330282121897
  saturation: 0.8873428134247661
  rhythmicContrast: 0.39339141780510545
purpose: []
